# Generated by Django 4.2.1 on 2023-07-09 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('pid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
                ('article', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.articles')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
