# Generated by Django 4.2.1 on 2023-07-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='article',
            new_name='body',
        ),
    ]
