# Generated by Django 4.2.1 on 2023-07-12 02:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_comments_article_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Ratings',
        ),
    ]
